apiVersion: batch/v1
kind: Job
metadata:
  name: candoo-migration-job-{{ image.tag }}
  namespace: {{ namespace }}
spec:
  template:
    spec:
      containers:
        - name: candoo-migration
          image: docker.repo.taavsystem.ir/service-charge-migrations:{{ image.tag }}
          envFrom:
            - secretRef:
                name: candoo-back-secret
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: private-repo