apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job-76ca8a57215
  namespace: candoo-test
spec:
  template:
    spec:
      containers:
        - name: candoo-migration
          image: docker.repo.taavsystem.ir/service-charge-argo-migrations:76ca8a57215
          envFrom:
            - secretRef:
                name: candoo-back-secret
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: private-repo